wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.5
    start_time: 1680516682.070284
    t:
      1:
      - 1
      - 5
      - 41
      - 51
      - 53
      - 55
      - 77
      3:
      - 13
      - 16
      - 23
      4: 3.9.5
      5: 0.14.0
      8:
      - 5
anchors:
  desc: null
  value: 7
embedding:
  desc: null
  value: Lipschitz_rw
epochs:
  desc: null
  value: 200
gpu:
  desc: null
  value: 2
model_name:
  desc: null
  value: graphsage
need_training:
  desc: null
  value: 'true'
norm:
  desc: null
  value: percentile
num_edges_samples:
  desc: null
  value: 50
num_layers:
  desc: null
  value: 2
num_times_samples:
  desc: null
  value: 50
pos_weight:
  desc: null
  value: 0.3
threshold:
  desc: null
  value: 0.5
train:
  desc: null
  value: test_data
trained_on:
  desc: null
  value: gap
